# Generated by Django 5.0.4 on 2024-05-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pierzada_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmessage',
            name='image',
            field=models.ImageField(default='none', upload_to='uploads', verbose_name='attached image'),
        ),
    ]
