# Generated by Django 5.0.4 on 2024-05-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pierzada_app', '0002_logmessage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='image',
            field=models.ImageField(default='none', upload_to='uploads'),
        ),
    ]
